### ISSUE TITLE
OCI Runtime Error

### ISSUE THREAD

**Issue by brentarias** [flakio/catalog#9]
I'm trying to follow the book "Microservices with Docker on Microsoft Azure".  On my Windows 10 Enterprise laptop, I installed Docker Toolbox v1.12.0 (not Docker for Windows).  Everything was fine until I used the Docker Quickstart terminal and tried this:

```
barias@LT-Arias MINGW64 ~/AzureDocker/catalog (master)
$ docker run -d -t -p 80:80 -e "server.url=http://*:80" -v /c/Users/barias/AzureDocker/catalog/Pr
oductCatalog/src/ProductCatalog:/app thedanfernandez/productcatalog
Unable to find image 'thedanfernandez/productcatalog:latest' locally
latest: Pulling from thedanfernandez/productcatalog

52747b744e22: Pull complete
a3ed95caeb02: Pull complete
bcdfa5245946: Pull complete
50df7d9be93c: Pull complete
5fc529821ea0: Pull complete
0892ffac4015: Pull complete
2f0ac65bae5c: Pull complete
437f6eeb9a92: Pull complete
1eae4c5be51c: Pull complete
6ffba4db4f42: Pull complete
4d87df863ea1: Pull complete
c294aa4525f0: Pull complete
Digest: sha256:88201e3cdb262a0883538027c52620732f9dbca69be2c45dd02bfc1cc7e1fafc
Status: Downloaded newer image for thedanfernandez/productcatalog:latest
8fb78fb9813d864a9cf044262d9d6746216b0273ebd031807105cd64781b1596
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: oci runtime error: no such file or directory.
```

Ok, so it failed due to an "oci runtime error".  Any idea of how to resolve this?

Running `docker info` in the same shell gives:

```
$ docker info
Containers: 3
Running: 1
Paused: 0
Stopped: 2
Images: 2
Server Version: 1.12.1
Storage Driver: aufs
Root Dir: /mnt/sda1/var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 40
Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge overlay host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: ZQ2R:FILX:2VY7:RS7D:BBTW:N3NF:DXGY:5AMO:MHS2:2YYW:7CNM:R7ZR
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
File Descriptors: 17
Goroutines: 30
System Time: 2016-09-19T19:53:31.8914195Z
EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
provider=virtualbox
Insecure Registries:
127.0.0.0/8
```

Incidentally, the prior container the book directed me to run had worked just fine.  For example:

```
$ docker run -d -p 9200:9200 elasticsearch
Unable to find image 'elasticsearch:latest' locally
latest: Pulling from library/elasticsearch
8ad8b3f87b37: Pull complete
751fe39c4d34: Pull complete
b165e84cccc1: Pull complete
acfcc7cbc59b: Pull complete
04b7a9efc4af: Pull complete
b16e55fe5285: Pull complete
8c5cbb866b55: Pull complete
53c3dd7fc70d: Pull complete
3de13756a8c8: Pull complete
64be422416b7: Pull complete
b808918635ce: Pull complete
5b3ceec8c156: Pull complete
561269d0b7cc: Pull complete
0c6cf9533753: Pull complete
Digest: sha256:0805f15d9dfa3ef5a32a0f43d3aad428adc0d6fa6576ffbcdd268f5ae40a4a2e
Status: Downloaded newer image for elasticsearch:latest
3600559ce2c60623f998777b117bed369903fdfd45ab0429425459839d24dc1e
```

I could not get Docker logs for the failed `docker run` command, but I can provide the docker log for the container that succeeded...which contains an interesting message about the kernel being out of date:

```
barias@LT-Arias MINGW64 ~/AzureDocker/catalog (master)
$ docker logs 3600559ce2
[2016-09-17 17:54:49,138][WARN ][bootstrap                ] unable to install syscall filter: seccomp unavailable: your kernel is buggy and you should upgrade
[2016-09-17 17:54:49,377][INFO ][node                     ] [Vibraxas] version[2.4.0], pid[1], build[ce9f0c7/2016-08-29T09:14:17Z]
[2016-09-17 17:54:49,377][INFO ][node                     ] [Vibraxas] initializing ...
[2016-09-17 17:54:50,023][INFO ][plugins                  ] [Vibraxas] modules [reindex, lang-expression, lang-groovy], plugins [], sites []
[2016-09-17 17:54:50,054][INFO ][env                      ] [Vibraxas] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda1)]], net usable_space [16.5gb], net total_space [17.8gb], spins? [possibly], types [ext4]
[2016-09-17 17:54:50,055][INFO ][env                      ] [Vibraxas] heap size [1015.6mb], compressed ordinary object pointers [true]
[2016-09-17 17:54:52,326][INFO ][node                     ] [Vibraxas] initialized
[2016-09-17 17:54:52,337][INFO ][node                     ] [Vibraxas] starting ...
[2016-09-17 17:54:52,462][INFO ][transport                ] [Vibraxas] publish_address {172.17.0.2:9300}, bound_addresses {[::]:9300}
[2016-09-17 17:54:52,465][INFO ][discovery                ] [Vibraxas] elasticsearch/4HNlKaTZR6i8DJBSvAPsHg
[2016-09-17 17:54:55,611][INFO ][cluster.service          ] [Vibraxas] new_master {Vibraxas}{4HNlKaTZR6i8DJBSvAPsHg}{172.17.0.2}{172.17.0.2:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
[2016-09-17 17:54:55,672][INFO ][gateway                  ] [Vibraxas] recovered [0] indices into cluster_state
[2016-09-17 17:54:55,673][INFO ][http                     ] [Vibraxas] publish_address {172.17.0.2:9200}, bound_addresses {[::]:9200}
[2016-09-17 17:54:55,673][INFO ][node                     ] [Vibraxas] started
```

Not sure if that "buggy kernel" message could be related; just an FYI.

Any ideas of what this "oci runtime" error is and how to fix would be much appreciated.

**Comment by thedanfernandez** [comment]
Just a quick note that I'm investigating here...

**Comment by satonaoki** [comment]
I'm trying to run this on "Docker for Windows" (stable and beta), and have a same error.

Here is a error message in debug-enabled Docker for Windows beta:

C:\Users\user\Documents\DockerBook>docker run -d -t -p 8080:80 -e "server.urls=http://*:80" -v c:/Users/user/Documents/DockerBook/ProductCatalog/ProductCatalog/src/ProductCatalog:/app thedanfernandez/productcatalog
2b38515d616459684b2cd62600c3d9409f43f9f95d8fb319a20d439138799647
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"chdir to cwd (\\"/app/ProductCatalog\\") set in config.json failed: no such file or directory\"\n".

**Comment by satonaoki** [comment]
And I have a same error on Docker on Ubuntu (on Azure VM):

docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"chdir to cwd (\\"/app/ProductCatalog\\") set in config.json failed: no such file or directory\"\n".

**Comment by bmscholl** [comment]
Hi Satonaoki, sorry for the delay. We'll look into this and get back to you asap.

**Comment by serjkazhura** [comment]
Having the same problem, any solutions yet?
Thanks

**Comment by tatekami-rightpath** [comment]
Any progress on this issue? I've got same error with satonaoki on my Docker for Windows.

**Comment by trentmswanson** [comment]
The error seems to indicate that Docker is unable to access the host directory.  The directory does not exist or the Docker daemon does not have permissions to access the folder. You would receive this exception if the ProductCatalog folder did not exist in the directory at the host mount. So, for example if you were mounting with something like `-v /hostpath:/app` and there was no folder named `ProductCatalog` under `/hostpath` you would receive this exception. The reason is that Docker is trying to set a working directory to a folder inside a volume mount where the folder does not exist.  The way the mount is setup is not necessarily good practice in my opinion, but that's being fixed as part of the content updates.

In the snippet @brentarias sent, `docker run -d -t -p 80:80 -e "server.url=http://*:80" -v /c/Users/barias/AzureDocker/catalog/Pr
oductCatalog/src/ProductCatalog:/app thedanfernandez/productcatalog` You would need to make sure directory named `ProductCatalog` under the directory you are mounting.  I suspect you should have instead used run with parameters like so, `docker run -d -t -p 80:80 -e "server.url=http://*:80" -v /c/Users/barias/AzureDocker/catalog:/app thedanfernandez/productcatalog`

@satonaoki I suspect your command should look more like, `docker run -d -t -p 8080:80 -e "server.urls=http://*:80" -v c:/Users/user/Documents/DockerBook/ProductCatalog:/app thedanfernandez/productcatalog`. I noticed you have two levels of ProductCatalog folders.

There are multiple nested `ProductCatalog` folders, and right now I'm not certain which should be at root of the mount. @thedanfernandez which of the ProductCatalog folders in the sample should be at the root of the mount?

Also note that when using Docker for Windows you will need to make sure to enable volume mounting. You can do this by right-clicking on the Docker icon in the system tray and then clicking **Settings**.  From there you will need to select **Shared Drives** from the menu and check the drive the mount points to as **Shared**. Although the current version of Docker will give a different exception if this is the case.

**Comment by tatekami-rightpath** [comment]
Hi trentmswanson! Thank you for your advice!!! Now I can get same result with the book.

**Comment by kieronlanning** [comment]
After fighting with this for the best part of a day, I finally chanced upon this article. So now that problem is fixed, the container itself won't start with one of the following errors (based on _which_ ProductCatalog folder I use):

```
Error: Unable to load application or execute command 'Microsoft.AspNet.Server.Kestrel'.
Available commands: web.
```

or

```
Error: Unable to resolve project from /app/ProductCatalog
```

Any help/ guidance @thedanfernandez / @trentmswanson?
